jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Create external Docker network
        run: |
          docker network ls | grep ecommerce-network || docker network create ecommerce-network

      - name: Build and start containers
        run: docker-compose up --build -d